run-name: "generate-fuel-mock-data"
on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 10 * * *'  # 10:00 AM
    - cron: '0 18 * * *'  # 6:00 PM
    #   paths:  
    #     - '/../..'     ## path to firebase database
    #     - '!/../..'    ## path to excluded firebase database
    # schedule:
    #   - cron: ''
    # workflow_call:
    #   outputs:
    #     automatic-trigger:
    #       description: "the workflow is triggered automatically"
    #       value: "value"
    #     manual-trigger:
    #       description: "the workflow is triggered manually"
    #       value: "value"

jobs:
    run-workflow:
      runs-on: ubuntu-latest
      environment: main_env
      env:
        API_KEY: ${{ vars.API_KEY }}
        PROJECT_ID: ${{ vars.PROJECT_ID }}
        SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}

      steps:
        - name: "checkout-to-repo"
          uses: actions/checkout@v3

        - name: "generate-data"
          run: |
            echo "API_KEY: ${{ vars.API_KEY }}"
            echo "PROJECT_ID: ${{ env.PROJECT_ID }}"
            echo "SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}"
            cd .github/actions/generate-mock-data
            npm install
            npx ts-node src/index.ts
        
          # with:
            # env: main_env
          
      #   with:
      #     token: "" ## github secrets value

      # - name: generate-mock-data ## push-data-to-firebase
      #   run: generate-mock-data/dist/index.js ## github action that generate the mock data